### ISSUE TITLE
No users returned on ILdapSearchService's GetUsers

### ISSUE THREAD

**Issue by antoniolago** [UniStuttgart-VISUS/Visus.LdapAuthentication#18]
**Affected library**
- [X] Visus.LdapAuthentication
- [ ] Visus.DirectoryAuthentication

**Environment**
- Library version 2.0.0
- OS: Windows 11
- .NET: .NET 8
- LDAP Server: Active Directory

**Summary**
ILdapSearchService's GetUsers returns no entries

**What are you doing?**

My goal is to get all users from "diretores" group or all users in the SearchBase and then manually filter.

```
using Identity.Dominio.Models;
using Microsoft.AspNetCore.Mvc;
using SinproRS.Dominio.Models.Auth;
using Visus.Ldap;
using Visus.Ldap.Claims;
using Visus.LdapAuthentication;

namespace Identity.API.Controllers
{
    public class BuscaController : ControllerBase
    {
        private ILdapSearchService<CustomLdapUser, LdapGroup> _searchService;
        private readonly ILogger<BuscaController> _logger;
        public BuscaController(ILdapSearchService<CustomLdapUser, LdapGroup> searchService,
                                ILogger<BuscaController> logger)
        {
            _searchService = searchService;
            _logger = logger;
        }

        [HttpGet]
        [Route("diretores")]
        public async Task<IActionResult> GetDiretores()
        { 
            var diretores = _searchService.GetUsers();
            return Ok(diretores );
        }
    }
}
```

**What is the problem?**
GetUsers function doesn't return anything
diretores variable is always an empty list

**What behaviour did you expect?**
Given the SearchBases in AddLdapAuthentication, it should return all users below the base even without filter.

**Additional context**
I tried some filters but it didn't made any difference, ILdapAuthenticationService's LoginPrincipal work fine in this same project.

**Comment by crowbar27** [comment]
ILdapSearchService.GetUsers is part of the test suite and I use the parameterless regularly in production, so I think the problem is in the configuration. As the method does not throw, I guess that you provided valid credentials for the service. Are you sure about the search scopes you have configured? This is the only thing I can imagine right now. If you set the default naming context with sub scope as search root, do you get any results?

**Comment by antoniolago** [comment]
Oopsie, I was missing User/Password in the AddLdapAuthentication 🤦‍♂️
Adding those worked like a charm.
No throwed errors can be misguiding for unobservant ppl like me 😆, but anyway great work and thanks for this <3

**Comment by crowbar27** [comment]
I will reopen that as the search service should throw if it cannot authenticate. I need to investigate why this is not the case.

**Comment by crowbar27** [comment]
I had a look at the code and what is happening here is that the library will perform an anonymous bind if you do not specify a service account. Depending on the server configuration, this might succeed, but anonymous users most likely cannot read what you are interested in. After careful consideration, I still think this is the best we can do here, because if I disallow anonyomous binds, you just cannot do that at all. I have added a warning in the docs that failure to specify a service account will result in an anonymous bind, which in turn might not yield the expected results.
